import MenuIcon from "@/app/components/MenuIcon";
import "@/app/globals.css";
import { clsx } from "clsx";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Arrows from "./Arrows";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          "h-screen w-screen bg-dark flex relative",
        )}
      >
        <MenuIcon />
        <div
          id="root"
          className="w-full h-full mx-24 outline-light outline-4 overflow-hidden"
        >
          {children}
        </div>
        <Arrows />
      </body>
    </html>
  );
}
